# Generated by Django 5.2.7 on 2025-12-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0011_remove_employees_salary_employees_salary_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=50)),
                ('asset_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('asset_value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('aquisition_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_date', models.DateField(auto_now_add=True)),
                ('value_at_link', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.companyassets')),
            ],
        ),
    ]
