# Generated by Django 5.2.7 on 2025-12-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyassets',
            name='status',
            field=models.CharField(default='Active', max_length=100, null=True),
        ),
    ]
