# Generated by Django 5.2.7 on 2025-10-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='Zimbabwe', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
