# Generated by Django 5.2.7 on 2025-12-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_banks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banks',
            old_name='organizaton',
            new_name='organization',
        ),
    ]
