# Generated by Django 5.2.7 on 2025-10-29 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=50)),
                ('component_type', models.CharField(max_length=50)),
                ('calculation_method', models.CharField(max_length=100, null=True)),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=100)),
                ('grade_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryGradeComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('frequency', models.CharField(default='Monthly', max_length=100)),
                ('is_active', models.BooleanField(default=True, max_length=10)),
                ('component_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salaries.salarycomponents')),
                ('grade_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salaries.salarygrades')),
            ],
        ),
    ]
