# Generated by Django 5.2.7 on 2025-11-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarygradecomponents',
            name='is_active',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
