# Generated by Django 5.2.7 on 2025-11-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_alter_salarygradecomponents_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarygradecomponents',
            old_name='component_id',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='salarygradecomponents',
            old_name='grade_id',
            new_name='grade',
        ),
    ]
