# Generated by Django 5.2.7 on 2025-10-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_personPhone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('project', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(default='Zimbabwe', max_length=100)),
                ('department_id', models.CharField(max_length=10)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
