# Generated by Django 5.2.7 on 2025-10-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('dob', models.CharField(default='01/01/1960', max_length=100)),
                ('hire_date', models.CharField(max_length=100)),
                ('organization_id', models.CharField(max_length=100)),
                ('department_id', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('category', models.TextField(default='', null=True)),
                ('expense', models.DateField(default='', null=True)),
                ('approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
        ),
    ]
