# Generated by Django 5.2.7 on 2025-10-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='country',
            field=models.CharField(default='Zimbabwe', max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='nationality',
            field=models.CharField(default='Zimbabwean', max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
