# Generated by Django 5.2.7 on 2025-10-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='dob',
            field=models.CharField(default='01/01/1960', max_length=100),
        ),
    ]
