# Generated by Django 5.2.7 on 2025-10-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees_address_employees_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
