# Generated by Django 5.2.5 on 2025-10-14 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.TextField(null=True)),
                ('interest_rate', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('balance', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
        ),
    ]
