# Generated by Django 5.2.7 on 2025-10-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employees_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(default='', max_length=200, null=True)),
                ('date', models.DateField(default='')),
                ('check_in', models.TimeField(default='')),
                ('check_out', models.TimeField(default='', null=True)),
                ('status', models.CharField(default='Present', max_length=100)),
            ],
        ),
    ]
