# Generated by Django 5.2.7 on 2025-10-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_attendance_check_in_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(null=True),
        ),
    ]
