# Generated by Django 5.2.7 on 2025-11-05 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_attendance_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('principal', models.CharField(max_length=200)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=1, max_digits=100)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=100)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=100)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=100)),
                ('payment_period', models.CharField(default='Monthly', max_length=100)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Tops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('balance_on_date', models.DecimalField(decimal_places=2, max_digits=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.loans')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('balance_on_date', models.DecimalField(decimal_places=2, max_digits=100)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.loans')),
            ],
        ),
    ]
