# Generated by Django 5.2.7 on 2025-11-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_loans_loan_tops_loan_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='months',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
