# Generated by Django 5.2.7 on 2025-11-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_loans_months'),
        ('salaries', '0002_alter_salarygradecomponents_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='salary',
        ),
        migrations.AddField(
            model_name='employees',
            name='salary_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salaries.salarygrades'),
        ),
        migrations.AddField(
            model_name='employees',
            name='salary_grade_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salaries.salarygradecomponents'),
        ),
    ]
